import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCylinder } from '@react-three/cannon'


// Auto-generated by: https://github.com/pmndrs/gltfjsx
const Wheel = forwardRef(({ radius = 0.25, leftSide, ...props }, ref) => {
  useCylinder(() => ({ mass: 1, type: 'Kinematic', material: 'wheel', collisionFilterGroup: 0, args: [radius, radius, 0.5, 26], ...props }), ref)
  return (
    <mesh ref={ref}>
      <mesh rotation={[0, 0, ((leftSide ? 1 : -1) * Math.PI) / 2]}>
       <cylinderGeometry args={[radius,radius,0.3,16]}/>
       <meshLambertMaterial color={"#333333"} />
      </mesh>
    </mesh>
  )
})

export default Wheel
